[project]
name = 'plum'
version = '0.0.1'
authors = [
  { name='Mark Liffiton', email='liffiton@gmail.com' }
]
readme = 'README'
requires-python = '>=3.9'

[tool.pytest.ini_options]
log_level = 'DEBUG'
testpaths = 'tests'
addopts = [
    "--import-mode=importlib",
    "-n8",
]
